spin_manifest_version = "1"
authors = ["Brian H <brian.hardock@fermyon.com>"]
description = "An example routing application"
name = "example"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "example"
source = "target/wasm32-wasi/release/example.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
